name: Notify Repository Y

on:
  push:
    branches:
      - master  # Aciona o workflow quando houver um push na branch master

jobs:
  notify:
    runs-on: ubuntu-latest  # Ambiente para rodar o workflow

    steps:
      - name: Trigger sync on Repository Y
        run: |
          # Envia uma solicitação POST para o GitHub API para disparar o evento no repositório Y
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "sync-repo"}' \
            https://api.github.com/repos/Hexcold/repy/dispatches
